"""
500 İngilizce-Türkçe kelimeyi veritabanına ekler.
Kullanım: python3 add_words.py
"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))

from app import app, db, Word, WordSample

WORDS = [
    # ── Sıfatlar ──────────────────────────────────────────────────────────────
    ("able",       "yetenekli"),
    ("absent",     "yok, mevcut değil"),
    ("accurate",   "doğru, kesin"),
    ("active",     "aktif, hareketli"),
    ("afraid",     "korkmuş"),
    ("angry",      "kızgın"),
    ("ancient",    "antik, çok eski"),
    ("beautiful",  "güzel"),
    ("bitter",     "acı, kızgın"),
    ("blind",      "kör"),
    ("boring",     "sıkıcı"),
    ("bright",     "parlak, zeki"),
    ("broken",     "kırık"),
    ("busy",       "meşgul"),
    ("calm",       "sakin"),
    ("careful",    "dikkatli"),
    ("cheap",      "ucuz"),
    ("cheerful",   "neşeli"),
    ("clean",      "temiz"),
    ("clear",      "açık, berrak"),
    ("clever",     "zeki, akıllı"),
    ("cold",       "soğuk"),
    ("comfortable","rahat"),
    ("complex",    "karmaşık"),
    ("confident",  "kendinden emin"),
    ("confused",   "kafası karışık"),
    ("correct",    "doğru"),
    ("coward",     "korkak"),
    ("cruel",      "zalim"),
    ("curious",    "meraklı"),
    ("dangerous",  "tehlikeli"),
    ("dark",       "karanlık"),
    ("dead",       "ölü"),
    ("dear",       "değerli, sevgili"),
    ("deep",       "derin"),
    ("delicious",  "lezzetli"),
    ("difficult",  "zor"),
    ("dirty",      "kirli"),
    ("dry",        "kuru"),
    ("dull",       "donuk, sıkıcı"),
    ("early",      "erken"),
    ("easy",       "kolay"),
    ("empty",      "boş"),
    ("enormous",   "devasa, çok büyük"),
    ("equal",      "eşit"),
    ("excited",    "heyecanlı"),
    ("expensive",  "pahalı"),
    ("fair",       "adil, açık renk"),
    ("faithful",   "sadık"),
    ("famous",     "ünlü"),
    ("fast",       "hızlı"),
    ("fat",        "şişman"),
    ("fierce",     "vahşi, şiddetli"),
    ("foolish",    "aptalca"),
    ("fresh",      "taze"),
    ("friendly",   "arkadaş canlısı"),
    ("funny",      "komik"),
    ("gentle",     "nazik"),
    ("glad",       "memnun"),
    ("glossy",     "parlak, cilalı"),
    ("gorgeous",   "muhteşem"),
    ("grateful",   "minnettar"),
    ("greedy",     "açgözlü"),
    ("guilty",     "suçlu"),
    ("happy",      "mutlu"),
    ("hard",       "sert, zor"),
    ("harsh",      "sert, acımasız"),
    ("healthy",    "sağlıklı"),
    ("heavy",      "ağır"),
    ("helpful",    "yardımsever"),
    ("honest",     "dürüst"),
    ("horrible",   "korkunç"),
    ("huge",       "devasa"),
    ("humble",     "mütevazı"),
    ("hungry",     "aç"),
    ("important",  "önemli"),
    ("innocent",   "masum"),
    ("jealous",    "kıskanç"),
    ("kind",       "nazik, kibar"),
    ("large",      "büyük"),
    ("lazy",       "tembel"),
    ("lively",     "canlı, enerjik"),
    ("lonely",     "yalnız"),
    ("loud",       "gürültülü"),
    ("lovely",     "sevimli"),
    ("lucky",      "şanslı"),
    ("magnificent","görkemli"),
    ("mean",       "kaba, ortalama"),
    ("messy",      "dağınık"),
    ("mighty",     "güçlü, zorlu"),
    ("modern",     "modern"),
    ("mysterious", "gizemli"),
    ("narrow",     "dar"),
    ("nervous",    "gergin"),
    ("noisy",      "gürültülü"),
    ("obvious",    "açık, belli"),
    ("ordinary",   "sıradan"),
    ("patient",    "sabırlı"),
    ("polite",     "kibar"),
    ("poor",       "fakir, zavallı"),
    ("powerful",   "güçlü"),
    ("proud",      "gururlu"),
    ("pure",       "saf, temiz"),
    ("quiet",      "sessiz"),
    ("rapid",      "hızlı"),
    ("rare",       "nadir"),
    ("rich",       "zengin"),
    ("rough",      "pürüzlü, sert"),
    ("rude",       "kaba"),
    ("sad",        "üzgün"),
    ("safe",       "güvenli"),
    ("serious",    "ciddi"),
    ("sharp",      "keskin"),
    ("shy",        "utangaç"),
    ("silent",     "sessiz"),
    ("silly",      "aptalca"),
    ("simple",     "basit"),
    ("slim",       "ince, zayıf"),
    ("slow",       "yavaş"),
    ("smart",      "akıllı"),
    ("smooth",     "pürüzsüz"),
    ("soft",       "yumuşak"),
    ("solid",      "sağlam, katı"),
    ("sorry",      "üzgün, özür dilerim"),
    ("strange",    "garip"),
    ("strong",     "güçlü"),
    ("stupid",     "aptal"),
    ("sudden",     "ani"),
    ("sweet",      "tatlı"),
    ("tall",       "uzun boylu"),
    ("tense",      "gergin"),
    ("terrible",   "korkunç, berbat"),
    ("thick",      "kalın"),
    ("thin",       "ince"),
    ("tired",      "yorgun"),
    ("tiny",       "minicik"),
    ("tough",      "sert, dayanıklı"),
    ("ugly",       "çirkin"),
    ("unique",     "benzersiz"),
    ("upset",      "üzgün, sinirli"),
    ("useful",     "kullanışlı"),
    ("vague",      "belirsiz"),
    ("violent",    "şiddetli"),
    ("warm",       "sıcak"),
    ("weak",       "zayıf"),
    ("weird",      "tuhaf"),
    ("wide",       "geniş"),
    ("wild",       "vahşi"),
    ("wise",       "bilge"),
    ("witty",      "nükteli, zeki"),
    ("wonderful",  "harika"),
    ("worthy",     "değerli, layık"),
    ("young",      "genç"),
    # ── Fiiller ───────────────────────────────────────────────────────────────
    ("accept",     "kabul etmek"),
    ("achieve",    "başarmak"),
    ("admit",      "itiraf etmek"),
    ("advise",     "tavsiye etmek"),
    ("agree",      "kabul etmek, anlaşmak"),
    ("allow",      "izin vermek"),
    ("announce",   "duyurmak"),
    ("answer",     "cevap vermek"),
    ("appear",     "görünmek"),
    ("argue",      "tartışmak"),
    ("arrive",     "varmak, ulaşmak"),
    ("ask",        "sormak"),
    ("avoid",      "kaçınmak"),
    ("begin",      "başlamak"),
    ("believe",    "inanmak"),
    ("borrow",     "ödünç almak"),
    ("break",      "kırmak"),
    ("bring",      "getirmek"),
    ("build",      "inşa etmek"),
    ("burn",       "yanmak, yakmak"),
    ("buy",        "satın almak"),
    ("call",       "aramak, çağırmak"),
    ("carry",      "taşımak"),
    ("catch",      "yakalamak"),
    ("change",     "değiştirmek"),
    ("choose",     "seçmek"),
    ("climb",      "tırmanmak"),
    ("close",      "kapatmak"),
    ("collect",    "toplamak"),
    ("come",       "gelmek"),
    ("compare",    "karşılaştırmak"),
    ("complete",   "tamamlamak"),
    ("connect",    "bağlamak"),
    ("consider",   "göz önünde bulundurmak"),
    ("continue",   "devam etmek"),
    ("control",    "kontrol etmek"),
    ("cook",       "pişirmek"),
    ("copy",       "kopyalamak"),
    ("count",      "saymak"),
    ("cover",      "örtmek, kapsamak"),
    ("create",     "yaratmak"),
    ("cry",        "ağlamak"),
    ("cut",        "kesmek"),
    ("decide",     "karar vermek"),
    ("describe",   "tarif etmek"),
    ("destroy",    "yok etmek"),
    ("develop",    "geliştirmek"),
    ("disagree",   "katılmamak"),
    ("discover",   "keşfetmek"),
    ("discuss",    "tartışmak, konuşmak"),
    ("divide",     "bölmek"),
    ("doubt",      "şüphe etmek"),
    ("draw",       "çizmek"),
    ("drop",       "düşürmek, bırakmak"),
    ("eat",        "yemek"),
    ("enjoy",      "keyif almak"),
    ("enter",      "girmek"),
    ("escape",     "kaçmak"),
    ("examine",    "incelemek"),
    ("exist",      "var olmak"),
    ("explain",    "açıklamak"),
    ("explore",    "keşfetmek"),
    ("fail",       "başarısız olmak"),
    ("fall",       "düşmek"),
    ("feel",       "hissetmek"),
    ("fight",      "dövüşmek, savaşmak"),
    ("find",       "bulmak"),
    ("finish",     "bitirmek"),
    ("fix",        "düzeltmek, onarmak"),
    ("fly",        "uçmak"),
    ("follow",     "takip etmek"),
    ("forget",     "unutmak"),
    ("forgive",    "affetmek"),
    ("give",       "vermek"),
    ("grow",       "büyümek"),
    ("guess",      "tahmin etmek"),
    ("happen",     "olmak, meydana gelmek"),
    ("hate",       "nefret etmek"),
    ("hear",       "duymak"),
    ("help",       "yardım etmek"),
    ("hide",       "saklamak"),
    ("hit",        "vurmak"),
    ("hold",       "tutmak"),
    ("hope",       "ummak"),
    ("hurt",       "acıtmak"),
    ("imagine",    "hayal etmek"),
    ("improve",    "geliştirmek"),
    ("include",    "dahil etmek"),
    ("increase",   "artırmak"),
    ("invite",     "davet etmek"),
    ("join",       "katılmak"),
    ("jump",       "atlamak"),
    ("keep",       "tutmak, saklamak"),
    ("know",       "bilmek"),
    ("laugh",      "gülmek"),
    ("lead",       "liderlik etmek, yönlendirmek"),
    ("learn",      "öğrenmek"),
    ("leave",      "ayrılmak, bırakmak"),
    ("lift",       "kaldırmak"),
    ("listen",     "dinlemek"),
    ("live",       "yaşamak"),
    ("look",       "bakmak"),
    ("lose",       "kaybetmek"),
    ("love",       "sevmek"),
    ("make",       "yapmak, üretmek"),
    ("manage",     "yönetmek, başarmak"),
    ("meet",       "tanışmak, buluşmak"),
    ("miss",       "özlemek, kaçırmak"),
    ("move",       "taşınmak, hareket etmek"),
    ("need",       "ihtiyaç duymak"),
    ("notice",     "fark etmek"),
    ("offer",      "teklif etmek"),
    ("open",       "açmak"),
    ("order",      "sipariş vermek, emretmek"),
    ("pass",       "geçmek"),
    ("pay",        "ödemek"),
    ("plan",       "planlamak"),
    ("play",       "oynamak"),
    ("practice",   "pratik yapmak"),
    ("prepare",    "hazırlamak"),
    ("prevent",    "önlemek"),
    ("promise",    "söz vermek"),
    ("protect",    "korumak"),
    ("prove",      "kanıtlamak"),
    ("provide",    "sağlamak"),
    ("pull",       "çekmek"),
    ("push",       "itmek"),
    ("put",        "koymak"),
    ("reach",      "ulaşmak"),
    ("read",       "okumak"),
    ("realize",    "fark etmek, anlamak"),
    ("receive",    "almak"),
    ("remember",   "hatırlamak"),
    ("remove",     "kaldırmak, çıkarmak"),
    ("repeat",     "tekrarlamak"),
    ("replace",    "değiştirmek, yerine koymak"),
    ("respect",    "saygı göstermek"),
    ("return",     "dönmek, iade etmek"),
    ("run",        "koşmak"),
    ("save",       "kurtarmak, kaydetmek"),
    ("search",     "aramak"),
    ("seem",       "görünmek"),
    ("sell",       "satmak"),
    ("send",       "göndermek"),
    ("share",      "paylaşmak"),
    ("shout",      "bağırmak"),
    ("show",       "göstermek"),
    ("sing",       "şarkı söylemek"),
    ("sleep",      "uyumak"),
    ("solve",      "çözmek"),
    ("speak",      "konuşmak"),
    ("spend",      "harcamak, geçirmek"),
    ("stand",      "ayakta durmak"),
    ("start",      "başlamak"),
    ("stay",       "kalmak"),
    ("stop",       "durmak"),
    ("study",      "çalışmak"),
    ("suggest",    "önermek"),
    ("support",    "desteklemek"),
    ("swim",       "yüzmek"),
    ("take",       "almak"),
    ("talk",       "konuşmak"),
    ("teach",      "öğretmek"),
    ("tell",       "söylemek"),
    ("think",      "düşünmek"),
    ("travel",     "seyahat etmek"),
    ("try",        "denemek"),
    ("turn",       "dönmek, çevirmek"),
    ("understand", "anlamak"),
    ("use",        "kullanmak"),
    ("wait",       "beklemek"),
    ("wake",       "uyanmak"),
    ("walk",       "yürümek"),
    ("want",       "istemek"),
    ("warn",       "uyarmak"),
    ("watch",      "izlemek"),
    ("win",        "kazanmak"),
    ("wish",       "dilemek"),
    ("wonder",     "merak etmek"),
    ("work",       "çalışmak"),
    ("worry",      "endişelenmek"),
    ("write",      "yazmak"),
    # ── İsimler — Nesneler ────────────────────────────────────────────────────
    ("bag",        "çanta"),
    ("ball",       "top"),
    ("bed",        "yatak"),
    ("bell",       "zil, çan"),
    ("bicycle",    "bisiklet"),
    ("bottle",     "şişe"),
    ("bowl",       "kase"),
    ("box",        "kutu"),
    ("bridge",     "köprü"),
    ("brush",      "fırça"),
    ("button",     "düğme"),
    ("camera",     "fotoğraf makinesi"),
    ("candle",     "mum"),
    ("card",       "kart"),
    ("carpet",     "halı"),
    ("chain",      "zincir"),
    ("chair",      "sandalye"),
    ("clock",      "saat"),
    ("coin",       "madeni para"),
    ("computer",   "bilgisayar"),
    ("crown",      "taç"),
    ("cup",        "bardak, fincan"),
    ("curtain",    "perde"),
    ("desk",       "masa"),
    ("door",       "kapı"),
    ("drawer",     "çekmece"),
    ("drum",       "davul"),
    ("flag",       "bayrak"),
    ("floor",      "zemin, kat"),
    ("flower",     "çiçek"),
    ("fork",       "çatal"),
    ("gate",       "kapı, demir kapı"),
    ("glass",      "cam, bardak"),
    ("gun",        "silah"),
    ("hammer",     "çekiç"),
    ("hat",        "şapka"),
    ("hook",       "kanca"),
    ("jar",        "kavanoz"),
    ("key",        "anahtar"),
    ("knife",      "bıçak"),
    ("ladder",     "merdiven"),
    ("lamp",       "lamba"),
    ("lock",       "kilit"),
    ("map",        "harita"),
    ("mask",       "maske"),
    ("mirror",     "ayna"),
    ("needle",     "iğne"),
    ("net",        "ağ"),
    ("newspaper",  "gazete"),
    ("notebook",   "defter"),
    ("pen",        "kalem"),
    ("pencil",     "kurşun kalem"),
    ("phone",      "telefon"),
    ("picture",    "resim, fotoğraf"),
    ("pillow",     "yastık"),
    ("pipe",       "boru"),
    ("plate",      "tabak"),
    ("pocket",     "cep"),
    ("pot",        "tencere"),
    ("purse",      "çanta, cüzdan"),
    ("ring",       "yüzük, zil"),
    ("rope",       "ip, halat"),
    ("ruler",      "cetvel"),
    ("scissors",   "makas"),
    ("shelf",      "raf"),
    ("shirt",      "gömlek"),
    ("shoe",       "ayakkabı"),
    ("sink",       "lavabo"),
    ("sofa",       "kanepe"),
    ("spoon",      "kaşık"),
    ("stairs",     "merdiven"),
    ("stamp",      "pul, damga"),
    ("table",      "masa"),
    ("ticket",     "bilet"),
    ("torch",      "el feneri"),
    ("towel",      "havlu"),
    ("toy",        "oyuncak"),
    ("umbrella",   "şemsiye"),
    ("wallet",     "cüzdan"),
    ("watch",      "kol saati"),
    ("wheel",      "tekerlek"),
    ("whistle",    "düdük"),
    ("window",     "pencere"),
    ("wire",       "tel, kablo"),
    # ── İsimler — Doğa & Yer ─────────────────────────────────────────────────
    ("beach",      "plaj"),
    ("cave",       "mağara"),
    ("cliff",      "uçurum"),
    ("coast",      "kıyı"),
    ("desert",     "çöl"),
    ("dust",       "toz"),
    ("earth",      "yer, toprak, dünya"),
    ("field",      "tarla, alan"),
    ("fire",       "ateş"),
    ("fog",        "sis"),
    ("forest",     "orman"),
    ("frost",      "kırağı, buz"),
    ("garden",     "bahçe"),
    ("ground",     "yer, zemin"),
    ("harbor",     "liman"),
    ("hill",       "tepe"),
    ("horizon",    "ufuk"),
    ("ice",        "buz"),
    ("island",     "ada"),
    ("jungle",     "orman, cangıl"),
    ("lake",       "göl"),
    ("land",       "arazi, kara"),
    ("leaf",       "yaprak"),
    ("lightning",  "şimşek"),
    ("moon",       "ay"),
    ("mountain",   "dağ"),
    ("mud",        "çamur"),
    ("ocean",      "okyanus"),
    ("path",       "yol, patika"),
    ("plain",      "ova"),
    ("plant",      "bitki"),
    ("pond",       "gölet"),
    ("rain",       "yağmur"),
    ("rainbow",    "gökkuşağı"),
    ("rock",       "kaya"),
    ("root",       "kök"),
    ("sand",       "kum"),
    ("sea",        "deniz"),
    ("seed",       "tohum"),
    ("shadow",     "gölge"),
    ("shore",      "kıyı"),
    ("sky",        "gökyüzü"),
    ("smoke",      "duman"),
    ("snow",       "kar"),
    ("soil",       "toprak"),
    ("spring",     "ilkbahar, pınar"),
    ("star",       "yıldız"),
    ("stream",     "dere, akarsu"),
    ("sun",        "güneş"),
    ("thunder",    "gök gürültüsü"),
    ("tide",       "gelgit"),
    ("tree",       "ağaç"),
    ("valley",     "vadi"),
    ("volcano",    "yanardağ"),
    ("waterfall",  "şelale"),
    ("wave",       "dalga"),
    ("wind",       "rüzgar"),
    ("wood",       "ahşap, orman"),
    ("world",      "dünya"),
    # ── İsimler — Soyut & Diğer ───────────────────────────────────────────────
    ("ability",    "yetenek"),
    ("adventure",  "macera"),
    ("age",        "yaş, çağ"),
    ("anger",      "öfke"),
    ("answer",     "cevap"),
    ("art",        "sanat"),
    ("beauty",     "güzellik"),
    ("choice",     "seçim"),
    ("courage",    "cesaret"),
    ("culture",    "kültür"),
    ("danger",     "tehlike"),
    ("darkness",   "karanlık"),
    ("decision",   "karar"),
    ("defeat",     "yenilgi"),
    ("desire",     "arzu, istek"),
    ("duty",       "görev"),
    ("education",  "eğitim"),
    ("effort",     "çaba, efor"),
    ("emotion",    "duygu"),
    ("energy",     "enerji"),
    ("event",      "olay, etkinlik"),
    ("experience", "deneyim"),
    ("failure",    "başarısızlık"),
    ("faith",      "inanç"),
    ("fame",       "şöhret"),
    ("fate",       "kader"),
    ("fear",       "korku"),
    ("feeling",    "his, duygu"),
    ("freedom",    "özgürlük"),
    ("friend",     "arkadaş"),
    ("future",     "gelecek"),
    ("goal",       "hedef"),
    ("habit",      "alışkanlık"),
    ("happiness",  "mutluluk"),
    ("harm",       "zarar"),
    ("history",    "tarih"),
    ("honor",      "onur, şeref"),
    ("humor",      "mizah"),
    ("idea",       "fikir"),
    ("identity",   "kimlik"),
    ("illusion",   "yanılsama, illüzyon"),
    ("imagination","hayal gücü"),
    ("impact",     "etki"),
    ("influence",  "etki, nüfuz"),
    ("injustice",  "haksızlık"),
    ("intelligence","zeka"),
    ("interest",   "ilgi, faiz"),
    ("journey",    "yolculuk"),
    ("justice",    "adalet"),
    ("knowledge",  "bilgi"),
    ("language",   "dil"),
    ("law",        "yasa, hukuk"),
    ("leader",     "lider"),
    ("lesson",     "ders"),
    ("life",       "hayat"),
    ("limit",      "sınır"),
    ("loss",       "kayıp"),
    ("luck",       "şans"),
    ("memory",     "hafıza, anı"),
    ("message",    "mesaj"),
    ("mistake",    "hata"),
    ("moment",     "an"),
    ("mystery",    "gizem"),
    ("nature",     "doğa, tabiat"),
    ("news",       "haber"),
    ("nightmare",  "kabus"),
    ("opinion",    "görüş, fikir"),
    ("opportunity","fırsat"),
    ("pain",       "acı"),
    ("past",       "geçmiş"),
    ("pattern",    "desen, kalıp"),
    ("personality","kişilik"),
    ("poverty",    "yoksulluk"),
    ("power",      "güç, iktidar"),
    ("present",    "şimdiki zaman, hediye"),
    ("pride",      "gurur"),
    ("priority",   "öncelik"),
    ("problem",    "sorun"),
    ("progress",   "ilerleme"),
    ("purpose",    "amaç"),
    ("question",   "soru"),
    ("reality",    "gerçeklik"),
    ("reason",     "neden, akıl"),
    ("relationship","ilişki"),
    ("reputation", "itibar"),
    ("respect",    "saygı"),
    ("responsibility","sorumluluk"),
    ("reward",     "ödül"),
    ("risk",       "risk"),
    ("role",       "rol"),
    ("rule",       "kural"),
    ("secret",     "sır"),
    ("silence",    "sessizlik"),
    ("skill",      "beceri"),
    ("society",    "toplum"),
    ("solution",   "çözüm"),
    ("soul",       "ruh"),
    ("strength",   "güç, kuvvet"),
    ("success",    "başarı"),
    ("suffering",  "acı, ıstırap"),
    ("talent",     "yetenek"),
    ("thought",    "düşünce"),
    ("time",       "zaman"),
    ("tradition",  "gelenek"),
    ("trust",      "güven"),
    ("truth",      "gerçek"),
    ("value",      "değer"),
    ("victory",    "zafer"),
    ("vision",     "vizyon, görüş"),
    ("voice",      "ses"),
    ("war",        "savaş"),
    ("wealth",     "servet"),
    ("wisdom",     "bilgelik"),
    ("wish",       "dilek"),
    ("wonder",     "merak, hayranlık"),
]

def main():
    with app.app_context():
        existing = {w.eng_word.lower() for w in Word.query.all()}
        added = 0
        skipped = 0

        for eng, tur in WORDS:
            if eng.lower() in existing:
                skipped += 1
                continue
            w = Word(eng_word=eng, tur_word=tur)
            db.session.add(w)
            db.session.flush()
            existing.add(eng.lower())
            added += 1

        db.session.commit()
        print(f"✅ {added} kelime eklendi, {skipped} zaten vardı.")
        print(f"📚 Toplam kelime: {Word.query.count()}")

if __name__ == '__main__':
    main()
